config/routes.rb
Rails.application.routes.draw do

  root to:'top#index'
  get "dodai_inbu_osu_saiko_css" => "top#test"

  resources :users do
    collection { get "image", "complete"}
  end
  get "signup" => "users#new"

  resource :user_session, only: :create
  get "login" =>"user_sessions#new"
  delete "logout" => "user_sessions#destroy"
  get "logout" => "user_sessions#destroy"
  get "help" => "top#help"
  get "restack" => "top#restack"

  get "about" => "top#about"
  get "get_image" => "essays#get_image"

  resources :essays do #記事
    collection do
      get 'pickup'
      post 'search'
      get "question"
      get 'fav'
      get 'tag'
      get 'tags'
      post "title_search"
    end
  end
  post "comment" => "comments#create"

  resources :posts #つぶやき
	post 'img' => "imgs#upload"
	get 'img/:name' => "imgs#show"

  # マイページ
  resources :mypages, only: [:index] do
    collection { get "my_essay", "my_list","add_my_list", "my_post", "destroy_my_list","get_user_image" }
  end

  namespace :api, {format: "json"} do
    get "user" => "apis#user"
    post "adduser" => "apis#add_user"
    post "deleteuser" => "apis#delete_user"
    get "essay" => "apis#essay"
    post "addessay" =>"apis#add_essay"
    post "delete_essay" => "apis#delete_essay"
    post "getimage" => "apis#get_images"
    get "tags" => "apis#get_tags"
    post "addTag" => "apis#create_tag"
    post "deleteTag" => "apis#delete_tag"
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :essay
  default_scope {order("updated_at desc")}
end

app/models/essay.rb
class Essay < ActiveRecord::Base
  belongs_to :user
  has_many :image_eassys, :dependent => :destroy
  has_many :mylists , :dependent => :destroy
  has_many :tag_essays , :dependent => :destroy
  default_scope {order("updated_at desc")}

  def Essay.essay_create(user,params)
    essay = Essay.new()
    essay.text = params[:text]
    essay.title = params[:title]
    essay.pickup_f = params[:pickup_f]
    essay.user_id = user.id
    esssay.save()#返り値はtrue/false
    #essay 返り値をオブジェクトにしたい場合
  end

  def essay_comment(user,text)
    comment = Comment.new()
    comment.user_id = user.id
    comment.essay_id = self.id
    comment.text = text
    comment.save()
  end

  def add_image(image_id)
    image = Image.new()
    image.image_id = image_id
    image.essay_id = self.id
    image.save()
  end

  def add_tag(tags)
    tags.each do |tag_id|
      puts tag_id
      tag_essay = TagEssay.new()
      tag_essay.tag_id = tag_id
      tag_essay.essay_id = self.id
      tag_essay.save()
    end
  end

  def Essay.title_search(keyword)
    keyword = "%"+ keyword +"%"
    result = {
      pickup: nil,
      user_posts: nil
    }
    essays = Essay.where(["title LIKE ?",keyword])
    result[:pickup] = essays.where(pickup_f: true)
    result[:user_posts] = essays.where(pickup_f: false)
    result
  end

  def Essay.keyword_search(keyword)
    keyword = "%"+ keyword +"%"
    result = {
      pickup: nil,
      user_posts: nil
    }
    essays = Essay.where(["text LIKE ?",keyword])
    result[:pickup] = essays.where(pickup_f: true)
    result[:user_posts] = essays.where(pickup_f: false)
    result
  end
  
   def Essay.sugest_essays(current_user)
    rankerEssay = Proc.new {
      if current_user.blank? 
        mylist = Mylist.group(:essay_id).count().to_a.sort {|a, b| -(a[1].to_i <=> b[1].to_i)}
        mylist.map { |essay_id|
          Essay.find_by id: essay_id[0]
        }.compact.slice(0, 3)
      else
        Essay.where(question: true).limit 3
      end
    }
    if current_user.nil? then
      return rankerEssay.call
    end
    
    tag = current_user.tag_users.first
    if tag then
	   	userInfo = Usertag.find(tag.id)
	    parentsTags = Tag.where(name: userInfo.fage)
	    Essay.sugest_parent(parentsTags.first).concat(Essay.sugest_parent parentsTags.last).slice(0,3)
    else
      rankerEssay.call
    end
  end

  def Essay.sugest_parent(parent_tag) 
    if parent_tag.nil? then
      return []
    end
    parent_tag.tag_essays.map {|tag|
      Essay.find_by(id: tag.essay_id)
	 }.compact
  end
end

app/models/essay_img.rb
class EssayImg < ActiveRecord::Base
end

app/models/fav.rb
class Fav < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  def Fav.post_to_fav(user_id, post_id)
    fav = Fav.new()
    fav.user_id = user_id
    fav.post_id = post_id
    fav.save()
  end
end

app/models/image_essay.rb
class ImageEssay < ActiveRecord::Base
  belongs_to :essay
end

app/models/mylist.rb
class Mylist < ActiveRecord::Base
  belongs_to :user
  belongs_to :essay
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  def Post.create_post(text,user)
    post = Post.new()
    post.user_id = user.id
    post.content = text
    post.save()
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :tag_essays , :dependent => :destroy
  def Tag.seaching_essays(tag_id)
    tag = Tag.find(tag_id)
    result = tag.tag_essays.map { |tag_essay| tag_essay.essay }
  end
	
	def get_essays
		self.tag_essays.map do |essay|
			Essay.find_by(id: essay.essay_id)
		end
	end
end

app/models/tag_essay.rb
class TagEssay < ActiveRecord::Base
  belongs_to :tag
  belongs_to :essay
  # tag_id と essay_idの組み合わせがユニークになるように

end

app/models/tag_user.rb
class TagUser < ActiveRecord::Base
  belongs_to :usertag
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  # for authlogic
  acts_as_authentic do |c|
    c.login_field = :name
  end
  has_many :essays , :dependent => :destroy
  has_many :posts , :dependent => :destroy
  has_many :favs , :dependent => :destroy
  has_many :mylists , :dependent => :destroy
  has_one :image, class_name: "UserImage", dependent: :destroy
  has_many :tag_users , :dependent => :destroy

  accepts_nested_attributes_for :image, allow_destroy: true
  accepts_nested_attributes_for :tag_users, allow_destroy: true

  validates_acceptance_of :confirming
  after_validation :check_confirming

  def check_confirming
    errors.delete(:confirming)
    self.confirming = errors.empty? ? "1" : "0"
  end

  def User.add_mylist(user_id, essay_id)
    item = Mylist.new()
    item.user_id = user_id
    item.essay_id = essay_id
    item.save()
  end

  def fav_post(post_id)
    fav = Fav.new()
    fav.post_id = post_id
    fav.user_id = self.id
    fav.save;
  end

end

app/models/user_image.rb
class UserImage < ActiveRecord::Base
  belongs_to :user

  attr_accessor :uploaded_image

  IMAGE_TYPES = { "image/jpeg" => "jpg", "image/gif" => "gif",
                  "image/png" => "png" }

  def extension
    IMAGE_TYPES[content_type]
  end

  def uploaded_image=(image)
    self.content_type = convert_content_type(image.content_type)
    self.data = image.read
    @uploaded_image = image
  end

  private
    def convert_content_type(ctype)
      ctype = ctype.rstrip.downcase
      case ctype
      when "image/pjpeg" then "image/jpeg"
      when "image/jpg"   then "image/jpeg"
      when "image/x-png" then "image/png"
      else ctype
      end
    end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/models/usertag.rb
class Usertag < ActiveRecord::Base
  has_many :tag_users , :dependent => :destroy
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/favs_helper.rb
module FavsHelper
end

app/helpers/imgs_helper.rb
module ImgsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
  <div class="row">
              <div class="col l2 s12">
                <ul>
                    <li><%= link_to "ヘルプ", help_path, class: "grey-text text-lighten-3" %></li>
                    <li><%= link_to "サイトについて", about_path, class: "grey-text text-lighten-3" %></li>
                    <li><%= link_to "みんなの投稿", essays_path, class: "grey-text text-lighten-3" %></li>
                    <li><%= link_to "みんなの質問", question_essays_path, class: "grey-text text-lighten-3" %></li>
                    <li><%= link_to "特集", pickup_essays_path, class: "grey-text text-lighten-3" %></li>
                  </ul>
              </div>
            </div>
  </div>
    <div class="footer-copyright">
    <div class="container">
    &copy; Copyright  by ryt
    </div>
    </div>
</footer>
<%= javascript_include_tag "addjs/ryota.js" %>

app/views/layouts/_header.html.erb
    <nav>
      <div class="nav-wrapper container">
      <a class="brand-logo" >親こうfour</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <%= link_to "親こうfour", root_path, :class => "brand-logo" %>
 <!--      <%= link_to image_tag('/images/title.png', :class => "brand-logo", :id => 'title'), root_path %> -->
      <ul id="nav-mobile" class="right hide-on-med-and-down">
				<li><%= link_to "特集", pickup_essays_path %></li>
        <li><%= link_to "みんなの投稿", essays_path %></li>
      	        <li><%= link_to "サイトについて", about_path %></li>
			</ul>
        <ul class="side-nav" id="mobile-demo">
				<li><%= link_to "特集", pickup_essays_path %></li>
        <li><%= link_to "みんなの投稿", essays_path %></li>
				        <li><%= link_to "サイトについて", about_path %></li>
      </ul>
      </div>
      <div class="search" hidden>
        <div id="search_in">
        <%= form_tag('/essays/title_search',id: "search-bar") do %>
        <select id="select-search" name="example">
        <option value="/essays/title_search">タイトル</option>
        <option value="/essays/search">本文</option>
        </select>
          <%= text_field_tag 'keyword', "", placeholder: "キーワードを入力"  %>
          <%= submit_tag "検索" %>
          <a href="/essays/tags">タグ一覧へ</a>
        <% end %>
        </div>
      </div>
      <div class="clear">
      </div>
    </nav>
<%= javascript_include_tag "addjs/search_bar.js" %>

app/views/layouts/_sidebar.html.erb
<div class="sub">
<% if logged_in? %>
<div class="name">投稿管理</div>
  <ul class="sub_1">
    <li><%= link_to "記事投稿", new_essay_path %></li>
		<li class="beta"><%= link_to "記事投稿β版", new_essay_path+"?type=b",id: "beta" %></li>
    <li><%= link_to "自分の投稿", my_essay_mypages_path %></li>
    <li><%= link_to "お気に入り", my_list_mypages_path %></li>
  </ul>
    <div class="name">アカウント</div>
  <ul class="act">
    <li><%= link_to "マイページ", {:controller => "mypages", :action => "index"} %></li>
    <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
  </ul>
  <div class="clear"></div>

<% else %>

<div class="name_login">ログイン</div>

  <div id="top_log">
    <table class="logt">
      <%= form_for UserSession.new, url: user_session_path do |f| %>
<!--       <tr>
        <div class="error">
          <%= flash[:alert] %>
        </div>
      </tr> -->
      <tr>
        <td><%= f.text_field :name ,:class => 'log' ,:placeholder=> "name"%></td>
      </tr>
      <tr>
        <td><%= f.password_field :password ,:class => 'log', :placeholder => "pass"%></td>
      </tr>
    </table>

    <div id="logbt"><button value="button"><%= f.submit "ログイン"%></button></div>
    <% end %>
  </div>
<div class="name_login">初めての方</div>
<div id="new">
  <%= link_to "新規登録", signup_path, :id => "shinki" %>
</div>
<div class="clear"></div>
<% end %>

<div class="name" id="q_a">アンケート</div>
  <div id="ank">
    <div id="kaito">
      現在実施していません。
    </div>
  </div>
  <div class="clear"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>親こうfour</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
		  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag 'pc', media: 'screen and (min-width: 771px)', 'data-turbolinks-track' => true %>
<!--     <%= stylesheet_link_tag 'suma1', media: 'screen and (max-width: 770px) and (min-width: 0px)', 'data-turbolinks-track' => true %> -->
        <%= stylesheet_link_tag 'pc2', media: 'screen and (min-width: 771px)', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'suma2', media: 'screen and (max-width: 770px) and (min-width: 0px)', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'reset', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
  <div>
    <%= render "layouts/header" %>
    <article>
      <%= render "layouts/sidebar" %>
      <%= yield %>
    </article>
    <%= render "layouts/footer" %>
  </div>
</body>
</html>