config/routes.rb
Rails.application.routes.draw do

  root to:'top#index'
  get "dodai_inbu_osu_saiko_css" => "top#test"

  resources :users do
    collection { get "image", "complete"}
  end
  get "signup" => "users#new"

  resource :user_session, only: :create
  get "login" =>"user_sessions#new"
  delete "logout" => "user_sessions#destroy"
  get "logout" => "user_sessions#destroy"
  get "help" => "top#help"
  get "restack" => "top#restack"

  get "about" => "top#about"
  get "get_image" => "essays#get_image"

  resources :essays do #記事
    collection do
      get 'pickup'
      post 'search'
      get "question"
      get 'fav'
      get 'tag'
      get 'tags'
      post "title_search"
    end
  end
  post "comment" => "comments#create"

  resources :posts #つぶやき
	post 'img' => "imgs#upload"
	get 'img/:name' => "imgs#show"

  # マイページ
  resources :mypages, only: [:index] do
    collection { get "my_essay", "my_list","add_my_list", "my_post", "destroy_my_list","get_user_image" }
  end

  namespace :api, {format: "json"} do
    get "user" => "apis#user"
    post "adduser" => "apis#add_user"
    post "deleteuser" => "apis#delete_user"
    get "essay" => "apis#essay"
    post "addessay" =>"apis#add_essay"
    post "delete_essay" => "apis#delete_essay"
    post "getimage" => "apis#get_images"
    get "tags" => "apis#get_tags"
    post "addTag" => "apis#create_tag"
    post "deleteTag" => "apis#delete_tag"
  end
end

app/models/essay.rb
class Essay < ActiveRecord::Base
  belongs_to :user
  has_many :image_eassys, :dependent => :destroy
  has_many :mylists , :dependent => :destroy
  has_many :tag_essays , :dependent => :destroy
  default_scope {order("updated_at desc")}

  def Essay.essay_create(user,params)
    essay = Essay.new()
    essay.text = params[:text]
    essay.title = params[:title]
    essay.pickup_f = params[:pickup_f]
    essay.user_id = user.id
    esssay.save()#返り値はtrue/false
    #essay 返り値をオブジェクトにしたい場合
  end

  def essay_comment(user,text)
    comment = Comment.new()
    comment.user_id = user.id
    comment.essay_id = self.id
    comment.text = text
    comment.save()
  end

  def add_image(image_id)
    image = Image.new()
    image.image_id = image_id
    image.essay_id = self.id
    image.save()
  end

  def add_tag(tags)
    tags.each do |tag_id|
      puts tag_id
      tag_essay = TagEssay.new()
      tag_essay.tag_id = tag_id
      tag_essay.essay_id = self.id
      tag_essay.save()
    end
  end

  def Essay.title_search(keyword)
    keyword = "%"+ keyword +"%"
    result = {
      pickup: nil,
      user_posts: nil
    }
    essays = Essay.where(["title LIKE ?",keyword])
    result[:pickup] = essays.where(pickup_f: true)
    result[:user_posts] = essays.where(pickup_f: false)
    result
  end

  def Essay.keyword_search(keyword)
    keyword = "%"+ keyword +"%"
    result = {
      pickup: nil,
      user_posts: nil
    }
    essays = Essay.where(["text LIKE ?",keyword])
    result[:pickup] = essays.where(pickup_f: true)
    result[:user_posts] = essays.where(pickup_f: false)
    result
  end
  
   def Essay.sugest_essays(current_user)
    rankerEssay = Proc.new {
      if current_user.blank? 
        mylist = Mylist.group(:essay_id).count().to_a.sort {|a, b| -(a[1].to_i <=> b[1].to_i)}
        mylist.map { |essay_id|
          Essay.find_by id: essay_id[0]
        }.compact.slice(0, 3)
      else
        Essay.where(question: true).limit 3
      end
    }
    if current_user.nil? then
      return rankerEssay.call
    end
    
    tag = current_user.tag_users.first
    if tag then
	   	userInfo = Usertag.find(tag.id)
	    parentsTags = Tag.where(name: userInfo.fage)
	    Essay.sugest_parent(parentsTags.first).concat(Essay.sugest_parent parentsTags.last).slice(0,3)
    else
      rankerEssay.call
    end
  end

  def Essay.sugest_parent(parent_tag) 
    if parent_tag.nil? then
      return []
    end
    parent_tag.tag_essays.map {|tag|
      Essay.find_by(id: tag.essay_id)
	 }.compact
  end
end

app/controllers/essays_controller.rb
class EssaysController < ApplicationController
  def index
    @link_bool = false
    @new_essays = Essay.where.not(question: true).where(pickup_f: false).limit(3)
    @essays = Essay.where.not(question: true).where(pickup_f: false).offset(3)
    .paginate(:page => params[:page], :per_page => 4)
  end

  def fav
    @link_bool = true
    essayLength = Essay.where.not(question: true).where(pickup_f: false).map do |item|
      item.mylists.length
    end
    essays = Essay.where(pickup_f: false).where.not(question: true)
    essayArray = essays.map.with_index do |item, i|
      [item, essayLength[i]]
    end

    essayArray.reverse! do |item|
      item[1]
    end
    essayArray.map! do |item|
      item[0]
    end
    @new_essays = essayArray.slice(0,3)
    @essays = essayArray.slice(@new_essays.length, 4)
    render :template => 'essays/index'
  end

  def pickup
    @new_essays = Essay.where(pickup_f: true).limit(3)
    @essays = Essay.where(pickup_f: true).limit(-1).offset(3).paginate(:page => params[:page], :per_page => 8)
    #@essays = Essay.where(pickup_f: true)
    post_img = @essays.map {|essay| ImageEssay.where(essay_id: essay.id).first }
    @posts_img = post_img.map {|essay|
      if essay.nil? then
        re = 0
      else
        re =  essay.id
      end
      re
    }
  end

  def question
    @link_bool = false
    # tag_essays = TagEssay.where(tag_id: 1)
    # @test = tag_essays.map do |item|
    #   item.essay_id
    # end
    @questions = Essay.where(question: true).paginate(:page => params[:page], :per_page => 8)
  end

  def question_fav
    @link_bool = true
    tag_essays = TagEssay.where(tag_id: 1)
    @test = tag_essays.map do |item|
      item.essay_id
    end
    @questions = Essay.where(id: @test)
    render :template => 'essays/question'
  end

  def show
    @essay = Essay.find(params[:id])
    @user = @essay.user
    logger.debug @essay
    session[:essay_id] = params[:id]
    @images = ImageEssay.where(essay_id: @essay.id)
    middleTags = TagEssay.where(essay_id: @essay.id)
    @tags = middleTags.map { |tag| Tag.find_by id: tag.tag_id }
    @comments = Comment.where(essay_id: @essay.id)
    @mylist_num = @essay.mylists
		text = @essay.text.split "|"
    text.unshift("")
    if params[:page] then
      page = params[:page].to_i
      if text[page] then
        @essay.text = text[page]
        @now_page_num = page
        @page_num = text.length
      end
			else 
			@essay.text = text[1]
      @now_page_num = 1
      @page_num = text.length
    end
		
    if logged_in? then
      @fav = Mylist.where(user_id: current_user.id, essay_id: @essay.id)
      @fav = @fav[0]
    end
    post_img = ImageEssay.where(essay_id: @essay.id).first
      if post_img.nil? then
        re = 0
      else
        re =  post_img.id
      end
    re
    @essay_img = re

  end

  def tag_search #現状一つのタグに対してのみ
    tag_essays = TagEssay.where(tag_id: params[:tag_id])
    @essays = tag_essays.map { |essay| essay.essay }
    @essays.select! do |essay| 
      !essay.question
    end
  end

  def search
    @message = '検索キーワード: '+ params[:keyword]
    result = Essay.where.not(question: true)
    .keyword_search params[:keyword]
    pickups = result[:pickup]
    user_posts = result[:user_posts]
    @results = pickups.concat user_posts
  end

  def title_search
    @message = '検索キーワード: '+ params[:keyword]
    result = Essay.where.not(question: true)
    .title_search params[:keyword]
    pickups = result[:pickup]
    user_posts = result[:user_posts]
    @results = pickups.concat user_posts
    render :template => 'essays/search'
  end

  def new
    @image = ImageEssay.new
    @tags = Tag.all.offset(1)
    @essay = Essay.new
		if params[:type] == "b" then
			render(:layout => false,:template => "/essays/newmd")
		end
  end

  def create
    logger.debug params
    essay = Essay.new(essay_params)
    if !essay.pickup_f
      essay.pickup_f = false
    end
    essay.user_id = current_user.id
    if essay.save
      essay_id = essay.id
      images = {}
      image = {}
      logger.debug params
      upload_files = params[:image]
      if upload_files then
        upload_files.each do | file |
          logger.debug file[1]
          image[:img_name] = file[1].original_filename
          image[:image] = file[1].read
          @image = ImageEssay.new(image)
          @image.essay_id = essay_id
          @image.save
        end
      end
      redirect_to root_path
    else
      redirect_to new_essays_path
    end
    tags = params[:tags]
    if params[:tou] == "question" then
      essay.question = true
      essay.save
      essay.add_tag([1])
    end
    if tags then
      tags.uniq!
      essay.add_tag(params[:tags])
    end
  end

  def edit
    @essay = Essay.find(params[:id])
  end

  def update

  end

  def tags 
    split_tags = Proc.new {|tags, num|
      length = tags.length / num
      return_tags = []
      (0..(num-1)).to_a.each {|n|
        return_tags.push(tags.slice(n*length, length))
      }
      return_tags
    }
    tags = Tag.all
    @tags = split_tags.call(tags, 4)
  end

  def tag
    @message = '検索タグ: '
    @results = Essay.all
    if params[:tag_id] then
      tag_id = params[:tag_id]
      tag = Tag.find_by(id: tag_id)
      @message += tag.name
      @results = tag.tag_essays.map do |essay|
        Essay.find_by(id: essay.essay_id)
      end
    end
    render :template => search_essays_path
  end

  def destory
    logger.debug params
    @essay = Essay.find(params[:id]).delete
    render json: @essay
  end

  def get_image
    @image = ImageEssay.find_by(id: params[:id])
    logger.debug @image
    if @image then
      send_data(@image.image, :disposition => "inline", :type => "image/jpeg")
    else
      send_file("./public/images/no_img.png", :disposition => "inline", :type => "image/png")
    end
  end
  private
  def essay_params
    params.require(:essay).permit(:text,:title,:pickup_f)
  end
end

app/helpers/essays_helper.rb
module EssaysHelper
end

app/views/essays/index.html.erb
<div class="dodai">
  <div class="yohaku">
    <div class="minato_dai">
      <% @new_essays.each do |essay| %>
      <div class="minato_new">new!<br>
        <div class="minato_new_ko">
          <a href="/essays/<%= essay.id %>?page=1">
            <% if essay.user.image.present? %>
              <%= image_tag(url_for(:controller => 'users', :action => 'image', :id => essay.user.id), :size => '80x80',:class => 'tou_ti')%>
            <% else %>
              <%= image_tag '/images/sample_image.png', :size => '30x30' %>
            <% end %>
            <div class="mi_ti">
              <p class="mina_ti"><%= essay.title.slice(0,14)%></p>
            </div>
            <p class="mina_toko">
              <%= essay.text.slice(0,225)+" ..." %>
            </p>
          </a>
        </div>
      </div>
      <% end %>
    </div>

  <div class="minato_dai">
    <% @essays.each do |essay| %>
    <div class="minato_ki_ko">
      <a href="/essays/<%= essay.id %>?page=1">
        <% if essay.user.image.present? %>
          <%= image_tag(url_for(:controller => 'users', :action => 'image', :id => essay.user.id), :size => '80x80',:class => 'tou_ti')%>
        <% else %>
          <%= image_tag '/images/sample_image.png', :size => '30x30' %>
        <% end %>
        <div class="mi_ti">
          <!-- <img src="./.jpg" class="tou_ti"> -->
          <%= essay.title.slice(0,14) %>
        </div>
        <p class="mina_toko">
          <%= essay.text.slice(0,160)+" ..." %>
        </p>
      </a>
    </div>
    <% end %>
    <div class="page">
      <% if !@essays.kind_of?(Array) %>
        <%= will_paginate(@essays,:previous_label => "前", :next_label => "次") %>
      <% end %>
    </div>
  </div>
</div>
</div>
<div class="clear"></div>

app/views/essays/new.html.erb
<%= form_tag("/essays", :multipart => true ) do %>
<% if admin? then %>
<p>特集か否か<%= check_box_tag "essay[pickup_f]", "1" %></p>
<% end %>
<div class="dodai">
   <div class="yohaku2">
     <h2 class="top_title">記事投稿</h2>
      <div class="kijiwaku">
         <div class="kito">
            <%= text_field_tag 'essay[title]', "", class: "kijiti", placeholder: "タイトル" %>
            <%= text_area_tag 'essay[text]', "", class: "toran", placeholder: "本文" %>
            <%= file_field_tag 'image[0]' %>
         </div>
         <div class="taguwaku">
          <div id="check">
            <input type="radio" name="tou" value="essay" id="on" checked>
            <label for="on" class="switch-on">投稿</label>
            <input type="radio" name="tou" value="question" id="off">
            <label for="off" class="switch-off">質問</label>
            <div class="clear"></div>
          </div>
            <p class="ta">タグを選択</p>
            <div class="tawa">
              <p class="tata">孝行内容</p>
               <ul class="tagu">
               <% @tags[0,13].each do |i| %>
               <li>
               <%= check_box_tag 'tags[]', i.id, checked = false, :id => "tags_#{i.id}",:class => "checkbox" %>
               <%= i.name %>
               </li>
               <% end %>
               </ul>
          <div class="clear"></div>
               <p class="tata">イベント</p>
               <ul class="tagu">
                 <% @tags[13,11].each do |i| %>
                 <li>
                 <%= check_box_tag 'tags[]', i.id, checked = false, :id => "tags_#{i.id}",:class => "checkbox" %>
                 <%= i.name %>
                 </li>
                 <% end %>
               </ul>
          <div class="clear"></div>
          <p class="tata">季節</p>
          <ul class="tagu">
            <% @tags[24,4].each do |i| %>
            <li>
            <%= check_box_tag 'tags[]', i.id, checked = false, :id => "tags_#{i.id}",:class => "checkbox" %>
            <%= i.name %>
            </li>
            <% end %>
          </ul>
     <div class="clear"></div>
       <p class="tata">孝行場所</p>
       <ul class="tagu">
         <% @tags[28,2].each do |i| %>
         <li>
         <%= check_box_tag 'tags[]', i.id, checked = false, :id => "tags_#{i.id}",:class => "checkbox" %>
         <%= i.name %>
         </li>
         <% end %>
       </ul>
  <div class="clear"></div>
    <p class="tata">予算</p>
    <ul class="tagu">
      <% @tags[30,6].each do |i| %>
      <li>
      <%= check_box_tag 'tags[]', i.id, checked = false, :id => "tags_#{i.id}",:class => "checkbox" %>
      <%= i.name %>
      </li>
      <% end %>
    </ul>
  <div class="clear"></div>
  <p class="tata">孝行相手(父)の年代</p>
  <ul class="tagu">
    <% @tags[36,5].each do |i| %>
    <li>
    <%= check_box_tag 'tags[]', i.id, checked = false, :id => "tags_#{i.id}",:class => "checkbox" %>
    <%= i.name %>
    </li>
    <% end %>
  </ul>
<div class="clear"></div>
<p class="tata">孝行相手(母)の年代</p>
<ul class="tagu">
  <% @tags[41,5].each do |i| %>
  <li>
  <%= check_box_tag 'tags[]', i.id, checked = false, :id => "tags_#{i.id}",:class => "checkbox" %>
  <%= i.name %>
  </li>
  <% end %>
</ul>
<div class="clear"></div>
<p class="tata">あなたの職種</p>
<ul class="tagu">
  <% @tags[46,3].each do |i| %>
  <li>
  <%= check_box_tag 'tags[]', i.id, checked = false, :id => "tags_#{i.id}",:class => "checkbox" %>
  <%= i.name %>
  </li>
  <% end %>
</ul>
<div class="clear"></div>
<p class="tata">あなたの住んでる場所</p>
<ul class="tagu">
  <% @tags[49,2].each do |i| %>
  <li>
  <%= check_box_tag 'tags[]', i.id, checked = false, :id => "tags_#{i.id}",:class => "checkbox" %>
  <%= i.name %>
  </li>
  <% end %>
</ul>
<div class="clear"></div>

            </div>
         </div>
      </div>
         <%= submit_tag "投稿",:class => "sousin" ,:id => 'post-btn',style: "cursor: pointer" %>

   </div>

</div>
<% end %>
<div class="clear"></div>

<%= javascript_include_tag "addjs/essay_new.js" %>

app/views/essays/newmd.html.erb
 <head>
  <title>親こうfour β</title>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>
	<%= csrf_meta_tags %>
	   <%= stylesheet_link_tag 'ryo', 'data-turbolinks-track' => true %>
</head>
	
<body>
      <nav>
      <div class="nav-wrapper container">
      <a class="brand-logo"  >親こうfourβ</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <%= link_to "親こうfour", root_path, :class => "brand-logo" %>
 <!--      <%= link_to image_tag('/images/title.png', :class => "brand-logo", :id => 'title'), root_path %> -->
      <ul id="nav-mobile" class="right hide-on-med-and-down">
				<li><%= link_to "特集", pickup_essays_path %></li>
        <li><%= link_to "みんなの投稿", essays_path %></li>
      	<li><%= link_to "サイトについて", about_path %></li>
				<li><%= link_to "βページ", "http://sutpro.herokuapp.com/" %></li>
			</ul>
        <ul class="side-nav" id="mobile-demo">
				<li><%= link_to "特集", pickup_essays_path %></li>
        <li><%= link_to "みんなの投稿", essays_path %></li>
				        <li><%= link_to "サイトについて", about_path %></li>
      </ul>
      </div>
      <div class="search" hidden>
        <div id="search_in">
        <%= form_tag('/essays/title_search',id: "search-bar") do %>
        <select id="select-search" name="example">
        <option value="/essays/title_search">タイトル</option>
        <option value="/essays/search">本文</option>
        </select>
          <%= text_field_tag 'keyword', "", placeholder: "キーワードを入力"  %>
          <%= submit_tag "検索" %>
          <a href="/essays/tags">タグ一覧へ</a>
        <% end %>
        </div>
      </div>
      <div class="clear">
      </div>
    </nav>
    <%= javascript_tag do %>
    window.editor = {};
    window.editor.userId = <%= current_user.id %>;
    window.editor.redirect = "<%= raw root_path %>";
    window.editor.target  = "<%= img_path %>";
    window.editor.post = "<%= api_addessay_path %>";
    window.editor.admin = "<%= current_user.admin %>";
    console.log(window.editor)
  	<% end %>
  <main>
    <div id="app"></div>
  </main>
	<footer class="page-footer">
  <div class="container">
  <div class="row">
              <div class="col l2 s12">
                <ul>
                    <li><%= link_to "ヘルプ", help_path, class: "grey-text text-lighten-3" %></li>
                    <li><%= link_to "サイトについて", about_path, class: "grey-text text-lighten-3" %></li>
                    <li><%= link_to "みんなの投稿", essays_path, class: "grey-text text-lighten-3" %></li>
                    <li><%= link_to "みんなの質問", question_essays_path, class: "grey-text text-lighten-3" %></li>
                    <li><%= link_to "特集", pickup_essays_path, class: "grey-text text-lighten-3" %></li>
                  </ul>
              </div>
            </div>
  </div>
    <div class="footer-copyright">
    <div class="container">
    &copy; Copyright  by ryt
    </div>
    </div>
</footer>
<%= javascript_include_tag "addjs/ryota.js" %>

  <%= javascript_include_tag "addjs/mdEditer.js" %>
</body>
</html>

app/views/essays/pickup.html.erb
<div class="dodai">


  <div id="stage">
  	<input type="radio" id="back1" name="gal">
  	<input type="radio" id="back2" name="gal">
  	<input type="radio" id="back3" name="gal">
  	<input type="radio" id="back4" name="gal">
  	<input type="radio" id="back5" name="gal">
  	<input type="radio" id="next1" name="gal">
  	<input type="radio" id="next2" name="gal">
  	<input type="radio" id="next3" name="gal">
  	<input type="radio" id="next4" name="gal">
  	<input type="radio" id="next5" name="gal">
  		<div id="photos">
  			<div id="photo0" class="pic"><img src="/images/bana2.jpeg"></div>
  			<div id="photo1" class="pic"><%= link_to image_tag("/images/bana1.jpeg"), restack_path %></a>
  					<label for="back1"><div id="left1" class="b_left"><span>＜</span></div></label>
  					<label for="next1"><div id="right1" class="b_right"><span>＞</span></div></label>
  				</div>
  				<div id="photo2" class="pic"><img src="/images/bana2.jpeg">
  					<label for="back2"><div id="left2" class="b_left"><span>＜</span></div></label>
  					<label for="next2"><div id="right2" class="b_right"><span>＞</span></div></label>
  				</div>
  				<div id="photo3" class="pic"><img src="/images/bana3.jpeg">
  					<label for="back3"><div id="left3" class="b_left"><span>＜</span></div></label>
  					<label for="next3"><div id="right3" class="b_right"><span>＞</span></div></label>
  				</div>
  				<div id="photo4" class="pic"><%= link_to image_tag("/images/bana1.jpeg"), restack_path %></a>
  					<label for="back4"><div id="left4" class="b_left"><span>＜</span></div></label>
  					<label for="next4"><div id="right4" class="b_right"><span>＞</span></div></label>
  				</div>
  				<div id="photo5" class="pic"><img src="/images/bana2.jpeg">
  					<label for="back5"><div id="left5" class="b_left"><span>＜</span></div></label>
  					<label for="next5"><div id="right5" class="b_right"><span>＞</span></div></label>
  				</div>
  				<div id="photo6" class="pic"><a href="https://ecpskey.herokuapp.com/"><img src="/images/bana1.jpeg"></a>
  				</div>
  			</div>
  		<div style="padding:9%;"></div>
  	</div>

  <div class="yohaku">
    <div class="minato_dai">
      <% @new_essays.each_with_index do |essay, i| %>
      <div class="minato_new">new!<br>
        <div class="tokusyu_new_ko">
            <a href="/essays/<%= essay.id %>?page=1">
            <div class="mi_ti"><p class="mina_ti">
              <%= essay.title.slice(0,14)%></p>
            </div>
            <div class="topic_p">
              <%= image_tag(url_for(:controller => 'essays',:action => 'get_image', :id => @posts_img[i]), :class => "topic2") %>
            </div>
            <p class="toku_toko">
              <%= strip_tags(essay.text.html_safe.slice(0,75))+" ..." %>
            </p>
          </a>
        </div>
      </div>
      <% end %>
    </div>

  <div class="minato_dai">
    <% @essays.each do |essay| %>
    <div class="minato_ki_ko">
      <a href="/essays/<%= essay.id %>?page=1">
        <div class="mi_ti">
          <!-- <img src="./.jpg" class="tou_ti"> -->
          <%= essay.title.slice(0,10) %>
        </div>
        <p class="mina_toko">
          <%= strip_tags(essay.text.slice(0,160))+" ..." %>
        </p>
      </a>
    </div>
    <% end %>
    <div class="page">
      <%= will_paginate(@essays,:class => "pagenation",:previous_label => "前", :next_label => "次") %>
    </div>
  </div>
</div>
</div>
<div class="clear"></div>

app/views/essays/question.html.erb
<div class="dodai">
  <div class="yohaku">
    <div id="situ_dai">
      <% @questions.each do |item| %>
      <div class="situ_ko">
        <a href="/essays/<%= item.id%>?page=1">
          <div class="situ_icon">
          <% if item.user.image.present? %>
            <%= image_tag(url_for(:controller => 'users', :action => 'image', :id => item.user.id), :size => '80x80',:class => 'tou_ti')%>
          <% else %>
            <%= image_tag '/images/sample_image.png',:size => '80x80',:class => 'tou_ti'%>
          <% end %>
        </div>
          <%= item.title.slice(0,127) %></a></div>
          <% end %>
          <%= will_paginate(@questions, :previous_label => "前", :next_label => "次") %>
        </div>
      </div>
    </div>
    <div class="clear"></div>

app/views/essays/search.html.erb
<div class="dodai">
  <div class="yohaku">
    <h2><%= @message %></h2>
    <% @results.each do |item|%>
    <% if item %>
    <div class="minato_ki_ko">
      <a href="/essays/<%= item.id %>?page=1">
        <div class="mi_ti">
          <%= image_tag(url_for(:controller => 'users',:action => 'image', :id => item.user.id), :class => 'tou_ti')%>
          <p class="mina_ti"><%= item.title %></p>
        </div>
        <p class="mina_toku"><%= item.text.slice(0,60) %></p>
      </a>
    </div>
    <% end %>
    <% end %>
  </div>
</div>
<div class="clear"></div>

app/views/essays/tags.html.erb
<div class="dodai">
  <div class="yohaku">
		<div class="row">
    <% @tags.each do |tags| %>

		<div class="col-md-3">
    <ul class="list-group">
      <% tags.each do |tag| %>
      <li class="list-group-item">
        <a href="/essays/tag?tag_id=<%= tag.id%>"><div><%= tag.name %></div></a>
      </li>
      <% end %>
    </ul>
		</div>

    <% end %>
		</div>
  </div>
</div>
<div class="clear"></div>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">